### ISSUE TITLE
Make creating BlockchainDbMeta easier

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry-fork-db#21]
This type is only used to identify the Cache:

https://github.com/foundry-rs/alloy-fork-db/blob/e286594d83134a1191a97bbfb3a102a589f06706/src/cache.rs#L432-L432

this isn't very good, but we can make creating a SharedBackend easier at least by having helper functions on BlockchainDbMeta

https://github.com/alloy-rs/examples/pull/145/

**Comment by yash-atreya** [comment]
Closed by #22
