### ISSUE TITLE
Add sharedbackend blocking behaviour

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry-fork-db#3]
the current backend makes use of tokio's block in place per db request: https://github.com/foundry-rs/foundry-fork-db/blob/fd94eb5876da5afab266156c71654c49a304e338/src/backend.rs#L637-L644

this is inefficient, especially if the value is already cached, but convenient if used inside tokio.

we can make this configurable via some enum that determines if it should use block_in_place or not.

**Comment by Ethanol48** [comment]
I want to contribute to the project, can I get assigned to this issue?
